"""
Central glossary of every stat abbreviation shown anywhere on this
site, used to power hover tooltips (see app.py's `abbr` Jinja filter,
which wraps a label in `<abbr title="...">` when it has an entry here).

Keys must match the exact visible label text used in a template (case-
sensitive) for the filter to find them -- e.g. the leaderboard header
literally says "AVG", so the key here is "AVG", not "Avg" or "avg".
Add an entry here any time a new abbreviated label shows up in a
template; unrecognized labels just pass through unchanged rather than
breaking anything.
"""

GLOSSARY = {
    # counting stats
    "G": "Games Played",
    "GS": "Games Started",
    "PA": "Plate Appearances",
    "AB": "At Bats",
    "R": "Runs Scored",
    "H": "Hits",
    "2B": "Doubles",
    "3B": "Triples",
    "HR": "Home Runs",
    "HR/G": "Home Runs per Game (at this park)",
    "RBI": "Runs Batted In",
    "BB": "Walks (Base on Balls)",
    "SO": "Strikeouts",
    "K": "Strikeouts",
    "HBP": "Hit By Pitch",
    "TB": "Total Bases",
    "XBH": "Extra Base Hits",
    "SB": "Stolen Bases",
    "CS": "Caught Stealing",
    "W": "Wins",
    "L": "Losses",
    "SV": "Saves",
    "ER": "Earned Runs",
    "IP": "Innings Pitched",
    "BF": "Batters Faced",

    # rate / percentage stats
    "AVG": "Batting Average",
    "OBP": "On-Base Percentage",
    "SLG": "Slugging Percentage",
    "OPS": "On-Base Plus Slugging",
    "OPS+": "OPS Adjusted to League Average (100 = league average)",
    "ISO": "Isolated Power (Slugging minus Batting Average)",
    "wOBA": "Weighted On-Base Average",
    "BABIP": "Batting Average on Balls In Play",
    "BABIP Against": "Opponents' Batting Average on Balls In Play",
    "RC": "Runs Created",
    "RC/G": "Runs Created per Game",
    "Est. wRC": "Estimated Weighted Runs Created",
    "SecA": "Secondary Average",
    "K %": "Strikeout Percentage",
    "K%": "Strikeout Percentage",
    "BB %": "Walk Percentage",
    "BB%": "Walk Percentage",
    "K \u2212 BB %": "Strikeout Percentage Minus Walk Percentage",
    "K &minus; BB %": "Strikeout Percentage Minus Walk Percentage",
    "K-BB %": "Strikeout Percentage Minus Walk Percentage",
    "GB %": "Ground Ball Percentage",
    "GB%": "Ground Ball Percentage",
    "FB %": "Fly Ball Percentage",
    "FB%": "Fly Ball Percentage",
    "LD %": "Line Drive Percentage",
    "PU %": "Popup Percentage",
    "GB / FB Ratio": "Ground Ball to Fly Ball Ratio",
    "RISP": "Runners In Scoring Position",
    "LOB %": "Left On Base Percentage",
    "Left On Base %": "Percentage of Baserunners Stranded Without Scoring",

    # pitching
    "ERA": "Earned Run Average",
    "ERA+": "ERA Adjusted to League Average (100 = league average)",
    "ERA*": "Runs-Allowed-Based ERA (not earned-run-only \u2014 see page note)",
    "WHIP": "Walks Plus Hits per Inning Pitched",
    "FIP": "Fielding Independent Pitching",
    "xFIP": "Expected Fielding Independent Pitching",
    "K/9": "Strikeouts per 9 Innings",
    "BB/9": "Walks per 9 Innings",
    "HR/9": "Home Runs per 9 Innings",
    "QS": "Quality Starts",
    "Quality Starts": "Starts of 6+ Innings with 3 or Fewer Runs Allowed",

    # fielding
    "PO": "Putouts",
    "A": "Assists",
    "E": "Errors",
    "TC": "Total Chances",
    "RF": "Range Factor -- (Putouts + Assists) per Game at that position",
    "FPCT": "Fielding Percentage",
    "DP": "Double Plays",

    # team
    "R/G": "Runs per Game",
    "RA/G": "Runs Allowed per Game",
    "Run Diff": "Run Differential (Runs Scored minus Runs Allowed)",
    "Pythag Win %": "Pythagorean Win Percentage (expected win % from runs scored/allowed)",

    # additional Advanced-tab / percentile-bar terms
    "Walk %": "Walk Percentage",
    "Whiff %": "Swinging Strike Percentage (swings and misses as a share of pitches)",
    "Ground Ball %": "Ground Ball Percentage",
    "Fly Ball %": "Fly Ball Percentage",
    "BB / K Ratio": "Walk-to-Strikeout Ratio",
    "Ball %": "Percentage of Pitches Called a Ball",
    "Strike %": "Percentage of Pitches That Were Strikes",
    "Called Strike %": "Percentage of Pitches Taken for a Called Strike",
    "Swinging Strike %": "Percentage of Pitches Swung At and Missed",
    "First Pitch Strike %": "Percentage of Plate Appearances Starting with a Strike",
    "First Pitch Ball %": "Percentage of Plate Appearances Starting with a Ball",
    "First Pitch Swing %": "Percentage of Plate Appearances Where the Batter Swung at the First Pitch",
    "First Pitch Take %": "Percentage of Plate Appearances Where the Batter Took the First Pitch",
    "K Looking %": "Percentage of Plate Appearances Ending in a Called-Strike-Three Strikeout",
    "K Swinging %": "Percentage of Plate Appearances Ending in a Swinging Strikeout",
    "Extra Bases per Hit": "Total Bases Beyond First, Divided by Hits",
    "Stolen Base %": "Percentage of Stolen Base Attempts That Were Successful",
    "Starts": "Games Started (as a pitcher)",
    "Holds": "Relief Appearances That Preserved a Lead Without Finishing the Game",
    "Hold Rate": "Holds per Relief Appearance",
    "Blown Saves": "Save Opportunities Where the Lead Was Lost",
    "Save Opportunities": "Situations Where a Pitcher Could Record a Save",
    "Save Conversion %": "Percentage of Save Opportunities Successfully Converted",
    "Inherited Runners": "Baserunners on Base When a Relief Pitcher Enters the Game",
    "Inherited Runners Scored": "Inherited Runners Who Went On to Score",
    "Inherited Runner Scoring %": "Percentage of Inherited Runners Who Scored",
    "PA per Strikeout": "Plate Appearances per Strikeout",
    "PA per Walk": "Plate Appearances per Walk",
    "Opponent AVG": "Opponents' Batting Average",
    "Opponent OBP": "Opponents' On-Base Percentage",
    "Opponent SLG": "Opponents' Slugging Percentage",
    "Opponent OPS": "Opponents' On-Base Plus Slugging",
    "Opponent ISO": "Opponents' Isolated Power",
    "Opponent wOBA": "Opponents' Weighted On-Base Average",
}
